[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

##############################
# >>> Hatch Build Config <<< #
##############################

[project]
name = "reactpy_github_buttons"
description = "ReactPy wrapper for react-github-btn"
readme = "README.md"
keywords = ["React", "ReactJS", "ReactPy", "github", "buttons", "components"]
license = "MIT"
authors = [{ name = "Steve Jones", email = "jonesst2608@gmail.com" }]
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Widget Sets",
  "Topic :: Software Development :: User Interfaces",
  "Environment :: Web Environment",
  "Typing :: Typed",
]
dependencies = ["reactpy==2.0.0b4"]
dynamic = ["version"]
urls.Homepage = "https://github.com/stevej2608/reactpy-github-buttons"
urls.Repository = "https://github.com/stevej2608/reactpy-github-buttons"

[tool.hatch.version]
path = "reactpy_github_buttons/__init__.py"

[tool.hatch.build.targets.sdist]
include = ["/reactpy_github_buttons"]

[tool.hatch.build.targets.wheel]
packages = ["reactpy_github_buttons"]

[tool.hatch.metadata]
license-files = { paths = ["LICENSE"] }

[tool.hatch.envs.default]
installer = "uv"

#############################
# >>> Hatch Test Runner <<< #
#############################

[tool.hatch.envs.hatch-test]
extra-dependencies = [
  "anyio",
  "asgi-tools",
  "fastapi>=0.109.0",
  "orjson",
  "pillow>=10.2.0",
  "pixelmatch>=0.3.0",
  "playwright==1.41.1",
  "pytest-asyncio",
  "pytest-asyncio",
  "pytest-timeout==2.2.0",
  "servestatic",
  "starlette>=0.13.6",
  "trio>=0.24.0",
  "twine>=4.0.2",
  "uvicorn>=0.36.0",
  "websockets"
]
randomize = true
matrix-name-format = "{variable}-{value}"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.9", "3.10", "3.11", "3.12"]

#########################
# >>> Generic Tools <<< #
#########################

[tool.pytest.ini_options]
testpaths = "tests"
log_cli_level = "INFO"
filterwarnings = "ignore::DeprecationWarning"
addopts = "-rsxX -vv"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.mypy]
exclude = ["^\\.claude"]

[tool.pyright]
exclude = [".claude", ".venv","tmp"]
